apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue
    hello: world
  name: blue
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: jpetazzo/color
        name: color
        resources:
          requests:
            memory: 60M
        ports:
        - containerPort: 80
